### ISSUE TITLE
Objects in OCP already exists in Lab 7 

### ISSUE THREAD

**Issue by christianh814** [thoraxe/lab-ossm#10]
In the "Retries, Timeouts and Circuit Breaking" lab It tells you to create something that's already there.

```
[user5:~] $ oc create -n user5-tutorial -f /opt/app-root/workshop/content/src/istiofiles/virtual-service-recommendation-split.yml
virtualservice.networking.istio.io/recommendation created
Error from server (AlreadyExists): error when creating "/opt/app-root/workshop/content/src/istiofiles/virtual-service-recommendation-split.yml": destinationrules.networking.istio.io "recommendation" already exists
```

This is not a fatal error, but users might be confused. Might make a note about which "errors' are safe to ignore.

FWIW, I just used `oc replace -n userX-tutorial -f ...` to proceed without the warning.

**Comment by thoraxe** [comment]
should be fixed by #15
