### ISSUE TITLE
Issue working through Kiali’s View of Jaeger Distributed Tracing

### ISSUE THREAD

**Issue by canit00** [thoraxe/lab-ossm#5]
Whilst working through Kiali’s View of Jaeger Distributed Tracing - I don't see the `Distributed Tracing` option available. 

Also receive the following from the `Message Center` [1]

**Steps taken**
* Looked up route/URL for Jaeger UI
* Pulled up URL in browser and accepted self-signed certs
  * Noticed no distributed tracing option in Kiali UI
  * Noticed error from message center

Attempted to remedy issue by restarting stack - issue continues.

[1]
```
Could not fetch Jaeger info. Turning off Jaeger integration., Info: [ Jaeger URL in cluster is not set in Kiali configuration ]
10/28/20198:12:35 PM```

**Comment by danielhelfand** [comment]
Was just about to report the same thing. Here's a view of the options on the left side of the console: 

![image](https://user-images.githubusercontent.com/34258252/67772715-ec385600-fa30-11e9-90d3-6d7cec994da5.png)

**Comment by christianh814** [comment]
+1 for me too

**Comment by thoraxe** [comment]
Known issue. Is now resolved. Thanks!

**Comment by eskp** [comment]
@thoraxe What version of Kiali was this resolved in do you know?

**Comment by thoraxe** [comment]
No idea. I don't think it was a problem specific to Kiali but rather a configuration issue in our deployment of things.
